name: Collect Performance Metrics Scaling OMP

on:
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  job-template:
    strategy:
      max-parallel: 1
      matrix:
        size: [4096, 8192, 16384, 32768]
        sb: [32, 64]
        cores: [8, 16, 32]

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gspread
      run: pip install gspread oauth2client datetime pytz

    - name: "amd clang -fopenmp=libomp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; bash run_omp.sh clang "-fopenmp=libomp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" ${{ matrix.size }} ${{ matrix.sb }} ${{ matrix.cores }}' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "clang" "-fopenmp=libomp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" ${{ matrix.size }} ${{ matrix.sb }} ${{ matrix.cores }}
