name: Collect Performance Metrics

on:
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  collect_metrics:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gspread
      run: pip install gspread oauth2client datetime pytz

    - name: Execute file1.sh
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; bash run.sh gcc "-std=c17 -Wall -Wextra -O2"' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "gcc" "-std=c17 -Wall -Wextra -O2"

    - name: Execute file2.sh
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H zx81.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        ssh -i ssh_key cp202303@zx81.famaf.unc.edu.ar 'cd /home/cp2023/cp202303/navier-stokes/; bash run.sh gcc "-std=c17 -Wall -Wextra -O2"' > output_intel.txt
        rm ssh_key
        python write_to_sheet.py output_intel.txt $pkpass $GITHUB_SHA "n/d" "intel" "gcc" "-std=c17 -Wall -Wextra -O2"
