name: Collect Performance Metrics Scaling

on:
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  collect_metrics_scaling_lab2_atom:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gspread
      run: pip install gspread oauth2client datetime pytz

    - name: "amd aocc -std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=2"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; source /opt/AMD/aocc-compiler-4.0.0/setenv_AOCC.sh >/dev/null 2>&1; bash run.sh clang "-std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=2" "2048" ' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "aocc" "-std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=2"  "2048"
        
    - name: "amd aocc -std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=4"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; source /opt/AMD/aocc-compiler-4.0.0/setenv_AOCC.sh >/dev/null 2>&1; bash run.sh clang "-std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=4" "2048" ' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "aocc" "-std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=4" "2048"     
        
        
    - name: "amd aocc -std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=8"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; source /opt/AMD/aocc-compiler-4.0.0/setenv_AOCC.sh >/dev/null 2>&1; bash run.sh clang "-std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=8" "2048" ' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "aocc" "-std=c17 -Wall -Wextra -Ofast -march=native -Rpass=vectorize -Rpass-missed=vectorize -ffast-math -funsafe-math-optimizations -ftree-vectorize  -mllvm -force-vector-width=8"  "2048"


