name: Collect Performance Metrics Scaling OMP

on:
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  collect_metrics_scaling_lab3_atom_omp9:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gspread
      run: pip install gspread oauth2client datetime pytz

    - name: "amd gcc -fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra 2048 2 2"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; bash run_omp.sh gcc "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "8" "2"' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "gcc" "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "8" "2"

  collect_metrics_scaling_lab3_atom_omp12:
    needs: collect_metrics_scaling_lab3_atom_omp9
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gspread
      run: pip install gspread oauth2client datetime pytz

    - name: "amd gcc -fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra 2048 2 4"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; bash run_omp.sh gcc "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "2" "4"' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "gcc" "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "2" "4"

  collect_metrics_scaling_lab3_atom_omp15:
    needs: collect_metrics_scaling_lab3_atom_omp12
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gspread
      run: pip install gspread oauth2client datetime pytz

    - name: "amd gcc -fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra 2048 8 4"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; bash run_omp.sh gcc "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "8" "4"' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "gcc" "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "8" "4"

  collect_metrics_scaling_lab3_atom_omp18:
    needs: collect_metrics_scaling_lab3_atom_omp15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gspread
      run: pip install gspread oauth2client datetime pytz

    - name: "amd gcc -fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra 2048 2 8"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; bash run_omp.sh gcc "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "2" "8"' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "gcc" "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "2" "8"

  collect_metrics_scaling_lab3_atom_omp21:
    needs: collect_metrics_scaling_lab3_atom_omp18
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gspread
      run: pip install gspread oauth2client datetime pytz

    - name: "amd gcc -fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra 2048 8 8"
      env:
        pkpass: ${{secrets.PKPASSWORD}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 400 ssh_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H atom.famaf.unc.edu.ar >> ~/.ssh/known_hosts
        echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
        echo 'ServerAliveCountMax 6000' | tee -a ~/.ssh/config
        ssh -i ssh_key cp202303@atom.famaf.unc.edu.ar 'cd /users/cp2023/cp202303/navier-stokes/; bash run_omp.sh gcc "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "8" "8"' > output_amd.txt
        rm ssh_key
        python write_to_sheet.py output_amd.txt $pkpass $GITHUB_SHA "n/d" "amd" "gcc" "-fopenmp -std=c99 -march=native -Ofast -ftree-vectorize -Wall -Wextra" "2048" "8" "8"
  
